image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore ./src/GatheringApp/GatheringApp.csproj
      dotnet build --project ./src/GatheringApp/GatheringApp.csproj
  - name: Run
    command: dotnet run --project ./src/GatheringApp/GatheringApp.csproj

vscode:
  extensions:
    - muhammad-sammy.csharp